# Generated by Django 3.1.5 on 2021-01-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.CharField(default=1, max_length=100, verbose_name='예상 개발툴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
    ]
